"""autogenerated by genmsg_py from Sonar.msg. Do not edit."""
import roslib.message
import struct


class Sonar(roslib.message.Message):
  _md5sum = "bfb04bad3590e564c12fae1e3d9f10d9"
  _type = "Echoes/Sonar"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 north
float32 south
float32 east
float32 west

"""
  __slots__ = ['north','south','east','west']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       north,south,east,west
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Sonar, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.north is None:
        self.north = 0.
      if self.south is None:
        self.south = 0.
      if self.east is None:
        self.east = 0.
      if self.west is None:
        self.west = 0.
    else:
      self.north = 0.
      self.south = 0.
      self.east = 0.
      self.west = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.north, _x.south, _x.east, _x.west))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.north, _x.south, _x.east, _x.west,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.north, _x.south, _x.east, _x.west))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.north, _x.south, _x.east, _x.west,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_4f = struct.Struct("<4f")
