/***************************************************************************
                          point_list.h  -  description
                             -------------------
    begin                : Wed Sep 13 2000
    copyright            : (C) 2000 by Halva Giovanni & Giacomo
    email                : invehalv@airlab.elet.polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/


#ifndef point_list_h
#define point_list_h 1

#include "point_multimap.h"
#include "destroy_object.h"

#ifdef DMALLOC

#include <dmalloc.h>

#endif

/**
* This object collect the main points of a shape used to defuzzyfy the actions with the baricenter method.
* @short collection of point.
*/

class point_list : public point_multimap 
{
 public:
  /**
   * Constructor generated by the UML software used to build Brian. It return an empty point list.
   */
  point_list();

  /**
   * Copy constructor generated by the UML software used to build Brian. It return a copy of the point list.
   */
  point_list(const point_list &right);

  /**	
   * Destructor destroy a point list freeing all the point self-contained.
   */
  ~point_list();

  /**
   * Add a point into the list
   * @param apoint is the pointer to a point to add
   */
  void add_point (point * apoint);
};

#endif
