/***************************************************************************
                          assoc_file_parser.h  -  description
                             -------------------
    begin                : Wed Sep 13 2000
    copyright            : (C) 2000 by Halva Giovanni & Giacomo
    email                : invehalv@airlab.elet.polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
//	Specifies the classes used to fuzzyfy and defuzzyfy data



#ifndef assoc_file_parser_h
#define assoc_file_parser_h 1

#ifdef DMALLOC

#include <dmalloc.h>

#endif

#include "association_list.h"

/**
* Class that pars a file to read the association between crisp data and shapes or between commands and actions.
* @short read the associations
*/

class assoc_file_parser 
{
 public:
  /**
   * Constructor generated by the UML software used to build Brian. It return an empty assoc file parser.
   */
  assoc_file_parser();

  /**
   * Copy constructor generated by the UML software used to build Brian. It return a copy of the assoc file parser.
   */
  assoc_file_parser(const assoc_file_parser &right);

  /*
   * Constructor that build an assoc file parser that read the associations from file
   * @param file_name is the name of the file containing the associations
   */
  assoc_file_parser (char *file_name);

  /**	
   * Destructor destroy a assoc file parser: free the name of the file.
   */
  ~assoc_file_parser();

  /**
   * Method that read the associations from a file and return a pointer to the association list. It point to the original list so it must not be destroyed.
   * @return a pointer to a shape list
   */ 
  association_list * read_associations ();

  /**	
   * Return the name of the file containing the associations
   * @return a string
   */
  const char * get_name ();
  /**
   * Set the name of the file containing the shapes 
   * @param value is the name of the file
   */  
  void set_name (char * value);

 private:
  // Data Members for Class Attributes

      char *name;
};

// Class assoc_file_parser 

inline const char * assoc_file_parser::get_name ()
{
  return name;
}

inline void assoc_file_parser::set_name (char * value)
{
  if (name!=NULL) free(name);
  name = (char *) malloc(strlen(value)+1);
  strcpy(name,value);
}


#endif
