/* Auto-generated by genmsg_cpp for file /home/dave/RoboTower/IsAac/msg/MediaVarianza.msg */
#ifndef ISAAC_MESSAGE_MEDIAVARIANZA_H
#define ISAAC_MESSAGE_MEDIAVARIANZA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace IsAac
{
template <class ContainerAllocator>
struct MediaVarianza_ {
  typedef MediaVarianza_<ContainerAllocator> Type;

  MediaVarianza_()
  : Average(0.0)
  , Variance(0.0)
  , Time(0)
  {
  }

  MediaVarianza_(const ContainerAllocator& _alloc)
  : Average(0.0)
  , Variance(0.0)
  , Time(0)
  {
  }

  typedef float _Average_type;
  float Average;

  typedef float _Variance_type;
  float Variance;

  typedef uint32_t _Time_type;
  uint32_t Time;


private:
  static const char* __s_getDataType_() { return "IsAac/MediaVarianza"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b496fceed5ec68264fce67157b6713d7"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 Average\n\
float32 Variance\n\
uint32 Time\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Average);
    ros::serialization::serialize(stream, Variance);
    ros::serialization::serialize(stream, Time);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Average);
    ros::serialization::deserialize(stream, Variance);
    ros::serialization::deserialize(stream, Time);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Average);
    size += ros::serialization::serializationLength(Variance);
    size += ros::serialization::serializationLength(Time);
    return size;
  }

  typedef boost::shared_ptr< ::IsAac::MediaVarianza_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::IsAac::MediaVarianza_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MediaVarianza
typedef  ::IsAac::MediaVarianza_<std::allocator<void> > MediaVarianza;

typedef boost::shared_ptr< ::IsAac::MediaVarianza> MediaVarianzaPtr;
typedef boost::shared_ptr< ::IsAac::MediaVarianza const> MediaVarianzaConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::IsAac::MediaVarianza_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::IsAac::MediaVarianza_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace IsAac

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::IsAac::MediaVarianza_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::IsAac::MediaVarianza_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::IsAac::MediaVarianza_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b496fceed5ec68264fce67157b6713d7";
  }

  static const char* value(const  ::IsAac::MediaVarianza_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb496fceed5ec6826ULL;
  static const uint64_t static_value2 = 0x4fce67157b6713d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::IsAac::MediaVarianza_<ContainerAllocator> > {
  static const char* value() 
  {
    return "IsAac/MediaVarianza";
  }

  static const char* value(const  ::IsAac::MediaVarianza_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::IsAac::MediaVarianza_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 Average\n\
float32 Variance\n\
uint32 Time\n\
\n\
";
  }

  static const char* value(const  ::IsAac::MediaVarianza_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::IsAac::MediaVarianza_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::IsAac::MediaVarianza_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Average);
    stream.next(m.Variance);
    stream.next(m.Time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MediaVarianza_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::IsAac::MediaVarianza_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::IsAac::MediaVarianza_<ContainerAllocator> & v) 
  {
    s << indent << "Average: ";
    Printer<float>::stream(s, indent + "  ", v.Average);
    s << indent << "Variance: ";
    Printer<float>::stream(s, indent + "  ", v.Variance);
    s << indent << "Time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ISAAC_MESSAGE_MEDIAVARIANZA_H

