/***************************************************************************
                          div_triangle.h  -  description
                             -------------------
    begin                : Wed Sep 13 2000
    copyright            : (C) 2000 by Halva Giovanni & Giacomo
    email                : invehalv@airlab.elet.polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/


#ifndef div_triangle_h
#define div_triangle_h 1

#include "trapezium.h"

#ifdef DMALLOC

#include <dmalloc.h>

#endif


/**
* This class inherits from trapetium and specifies it to be a divided triangle. The get_membership_value, all the get and set methods are the same of trapezium.
* @see trapezium 
* @short Class implementing the concept of trapetium fuzzy set.
*/

class div_triangle : public trapezium  //## Inherits: div_triangle_inheritance%383D098901C2
{
 public:
  /**
   * Constructor generated by the UML software used to build Brian. It return an empty div_triangle.
   */  
  div_triangle();

  /**
   * Copy constructor generated by the UML software used to build Brian. It return a copy of the fuzzy set passed.
   */
  div_triangle(const div_triangle &right);

  /**	
   * Constructor that build a div_triangle.
   * @param alabel is the label given to the the fuzzy set
   * @param aa is the first point of the fuzzy set
   * @param ab is the second point of the fuzzy set
   * @param ac is the third point of the fuzzy set
   * @param ad is the fourth point of the fuzzy set
   */
  div_triangle (char* alabel, float aa, float ab, float ac, float ad);

  /**	
   * Destructor destroy a fuzzy set and free its data.
   */
  virtual ~div_triangle();
};


#endif
