/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget* create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *vbox1;
  GtkWidget *menubar2;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *nuovo1;
  GtkWidget *apri1;
  GtkWidget *salva1;
  GtkWidget *salva_come1;
  GtkWidget *separatormenuitem1;
  GtkWidget *esci1;
  GtkWidget *menuitem6;
  GtkWidget *menuitem6_menu;
  GtkWidget *crisp_data_list1;
  GtkWidget *fuzzy_data_list1;
  GtkWidget *weight_want_list1;
  GtkWidget *command_list1;
  GtkWidget *predicate_list1;
  GtkWidget *proposed_action_list1;
  GtkWidget *action_list1;
  GtkWidget *hide_all;
  GtkWidget *show_all;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about1;
  GtkWidget *vbox2;
  GtkWidget *title;
  GtkWidget *table1;
  GtkWidget *fuzzyassoc;
  GtkWidget *fuzzyshapes;
  GtkWidget *defuzzyassoc;
  GtkWidget *defuzzyshapes;
  GtkWidget *behaviors;
  GtkWidget *cando;
  GtkWidget *want;
  GtkWidget *pries;
  GtkWidget *actionpries;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *browse1;
  GtkWidget *browse2;
  GtkWidget *browse3;
  GtkWidget *browse4;
  GtkWidget *browse5;
  GtkWidget *browse6;
  GtkWidget *browse7;
  GtkWidget *browse8;
  GtkWidget *browse9;
  GtkWidget *hbuttonbox1;
  GtkWidget *addCrisp;
  GtkWidget *createBrian;
  GtkWidget *runBrian;
  GtkWidget *resetBrian;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mainWindow, 440, 350);
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("Mr.Brian Testing Enviroment"));
  gtk_window_set_default_icon_from_file ("brainicon.png",NULL);
  gtk_window_move(GTK_WINDOW(mainWindow),0,0);
  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_show (menubar2);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar2, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  nuovo1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (nuovo1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), nuovo1);

  apri1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (apri1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), apri1);

  salva1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (salva1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), salva1);

  salva_come1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (salva_come1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), salva_come1);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  esci1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (esci1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), esci1);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_Visualizza"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem6);

  menuitem6_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menuitem6_menu);

  crisp_data_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Crisp Data list"));
  gtk_widget_show (crisp_data_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), crisp_data_list1);

  fuzzy_data_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Fuzzy Data List"));
  gtk_widget_show (fuzzy_data_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), fuzzy_data_list1);

  weight_want_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Weight Want List"));
  gtk_widget_show (weight_want_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), weight_want_list1);

  command_list1 = gtk_check_menu_item_new_with_mnemonic (_("C_ommand List"));
  gtk_widget_show (command_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), command_list1);

  predicate_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Predicate List"));
  gtk_widget_show (predicate_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), predicate_list1);
  
  proposed_action_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Proposed Action List"));
  gtk_widget_show (proposed_action_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), proposed_action_list1);
  
  action_list1 = gtk_check_menu_item_new_with_mnemonic (_("_Action List"));
  gtk_widget_show (action_list1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), action_list1);
  
  hide_all = gtk_menu_item_new_with_mnemonic (_("_Hide All"));
  gtk_widget_show (hide_all);
  gtk_container_add( GTK_CONTAINER (menuitem6_menu), hide_all);
  
  show_all = gtk_menu_item_new_with_mnemonic (_("_Show All"));
  gtk_widget_show (show_all);
  gtk_container_add( GTK_CONTAINER (menuitem6_menu), show_all);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("Ai_uto"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar2), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  title = gtk_label_new (_("Seleziona i file di configurazione di Mr.Brian"));
  gtk_widget_show (title);
  gtk_box_pack_start (GTK_BOX (vbox2), title, FALSE, FALSE, 0);

  table1 = gtk_table_new (9, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  fuzzyassoc = gtk_label_new (_(" Fuzzyassoc"));
  gtk_widget_show (fuzzyassoc);
  gtk_table_attach (GTK_TABLE (table1), fuzzyassoc, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (fuzzyassoc), 0, 0.5);

    
  fuzzyshapes = gtk_label_new (_(" Fuzzyshapes"));
  gtk_widget_show (fuzzyshapes);
  gtk_table_attach (GTK_TABLE (table1), fuzzyshapes, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (fuzzyshapes), 0, 0.5);

  defuzzyassoc = gtk_label_new (_(" Defussyassoc"));
  gtk_widget_show (defuzzyassoc);
  gtk_table_attach (GTK_TABLE (table1), defuzzyassoc, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (defuzzyassoc), 0, 0.5);

  defuzzyshapes = gtk_label_new (_(" Defuzzyshapes"));
  gtk_widget_show (defuzzyshapes);
  gtk_table_attach (GTK_TABLE (table1), defuzzyshapes, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (defuzzyshapes), 0, 0.5);

  behaviors = gtk_label_new (_(" Behaviors"));
  gtk_widget_show (behaviors);
  gtk_table_attach (GTK_TABLE (table1), behaviors, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (behaviors), 0, 0.5);

  cando = gtk_label_new (_(" Cando"));
  gtk_widget_show (cando);
  gtk_table_attach (GTK_TABLE (table1), cando, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (cando), 0, 0.5);

  want = gtk_label_new (_(" Want"));
  gtk_widget_show (want);
  gtk_table_attach (GTK_TABLE (table1), want, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (want), 0, 0.5);

  pries = gtk_label_new (_(" Pries"));
  gtk_widget_show (pries);
  gtk_table_attach (GTK_TABLE (table1), pries, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pries), 0, 0.5);

  actionpries = gtk_label_new (_(" Actionpries"));
  gtk_widget_show (actionpries);
  gtk_table_attach (GTK_TABLE (table1), actionpries, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (actionpries), 0, 0.5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table1), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table1), entry3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table1), entry4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table1), entry5, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table1), entry6, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table1), entry7, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table1), entry8, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_table_attach (GTK_TABLE (table1), entry9, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse1 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse1);
  gtk_table_attach (GTK_TABLE (table1), browse1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse2 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse2);
  gtk_table_attach (GTK_TABLE (table1), browse2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse3 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse3);
  gtk_table_attach (GTK_TABLE (table1), browse3, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse4 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse4);
  gtk_table_attach (GTK_TABLE (table1), browse4, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse5 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse5);
  gtk_table_attach (GTK_TABLE (table1), browse5, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse6 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse6);
  gtk_table_attach (GTK_TABLE (table1), browse6, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse7 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse7);
  gtk_table_attach (GTK_TABLE (table1), browse7, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse8 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse8);
  gtk_table_attach (GTK_TABLE (table1), browse8, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse9 = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_show (browse9);
  gtk_table_attach (GTK_TABLE (table1), browse9, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  addCrisp = gtk_button_new_with_mnemonic (_("Add Crisp"));
  gtk_widget_show (addCrisp);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), addCrisp);
  GTK_WIDGET_SET_FLAGS (addCrisp, GTK_CAN_DEFAULT);

  createBrian = gtk_button_new_with_mnemonic (_("New Mr.Brian"));
  gtk_widget_show (createBrian);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), createBrian);
  GTK_WIDGET_SET_FLAGS (createBrian, GTK_CAN_DEFAULT);
  
  runBrian = gtk_button_new_with_mnemonic (_("Run Mr.Brian"));
  gtk_widget_show (runBrian);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), runBrian);
  GTK_WIDGET_SET_FLAGS (runBrian, GTK_CAN_DEFAULT);

  resetBrian = gtk_button_new_with_mnemonic (_("Reset Mr.Brian"));
  gtk_widget_show (resetBrian);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), resetBrian);
  GTK_WIDGET_SET_FLAGS (resetBrian, GTK_CAN_DEFAULT);

  
  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);
  
  //disattivo le voci inutili prima del run di brian
  gtk_widget_set_sensitive(crisp_data_list1,FALSE);
  gtk_widget_set_sensitive(fuzzy_data_list1,FALSE);
  gtk_widget_set_sensitive(weight_want_list1,FALSE);
  gtk_widget_set_sensitive(command_list1,FALSE);
  gtk_widget_set_sensitive(predicate_list1,FALSE);
  gtk_widget_set_sensitive(proposed_action_list1,FALSE);
  gtk_widget_set_sensitive(action_list1,FALSE);
  gtk_widget_set_sensitive(hide_all,FALSE);
  gtk_widget_set_sensitive(show_all,FALSE);
  gtk_widget_set_sensitive(addCrisp,FALSE);
  gtk_widget_set_sensitive(runBrian,FALSE);
  gtk_widget_set_sensitive(resetBrian,FALSE);
  

    
  //SEGNALI
  g_signal_connect ((gpointer) nuovo1, "activate",G_CALLBACK (on_nuovo1_activate),NULL);
  g_signal_connect ((gpointer) apri1, "activate",G_CALLBACK (on_apri1_activate),NULL);
  g_signal_connect ((gpointer) salva1, "activate",G_CALLBACK (on_salva1_activate),NULL);
  g_signal_connect ((gpointer) salva_come1, "activate",G_CALLBACK (on_salva_come1_activate),NULL);
  g_signal_connect ((gpointer) esci1, "activate",G_CALLBACK (on_esci1_activate),NULL);
  g_signal_connect ((gpointer) about1, "activate",G_CALLBACK (on_about1_activate),NULL);
  g_signal_connect ((gpointer) browse1, "clicked",G_CALLBACK (on_browse1_clicked),NULL);
  g_signal_connect ((gpointer) browse2, "clicked",G_CALLBACK (on_browse2_clicked),NULL);
  g_signal_connect ((gpointer) browse3, "clicked",G_CALLBACK (on_browse3_clicked),NULL);
  g_signal_connect ((gpointer) browse4, "clicked",G_CALLBACK (on_browse4_clicked),NULL);
  g_signal_connect ((gpointer) browse5, "clicked",G_CALLBACK (on_browse5_clicked),NULL);
  g_signal_connect ((gpointer) browse6, "clicked",G_CALLBACK (on_browse6_clicked),NULL);
  g_signal_connect ((gpointer) browse7, "clicked",G_CALLBACK (on_browse7_clicked),NULL);
  g_signal_connect ((gpointer) browse8, "clicked",G_CALLBACK (on_browse8_clicked),NULL);
  g_signal_connect ((gpointer) browse9, "clicked",G_CALLBACK (on_browse9_clicked),NULL);
  g_signal_connect ((gpointer) addCrisp, "clicked",G_CALLBACK (on_addCrisp_clicked),NULL);
  g_signal_connect ((gpointer) createBrian, "clicked",G_CALLBACK (on_createBrian_clicked),NULL);
  g_signal_connect ((gpointer) runBrian, "clicked",G_CALLBACK (on_runBrian_clicked),NULL);
  g_signal_connect ((gpointer) resetBrian, "clicked",G_CALLBACK (on_resetBrian_clicked),NULL);
  g_signal_connect (G_OBJECT(mainWindow),"delete_event",G_CALLBACK (on_esci1_activate),NULL);
  
  g_signal_connect ((gpointer) crisp_data_list1,"toggled",G_CALLBACK(on_crisp_data_list_toggle),NULL);
  g_signal_connect ((gpointer) fuzzy_data_list1,"toggled",G_CALLBACK(on_fuzzy_data_list_toggle),NULL);
  g_signal_connect ((gpointer) weight_want_list1,"toggled",G_CALLBACK(on_weight_want_list_toggle),NULL);
  g_signal_connect ((gpointer) predicate_list1,"toggled",G_CALLBACK(on_predicate_list_toggle),NULL);
  g_signal_connect ((gpointer) command_list1,"toggled",G_CALLBACK(on_command_list_toggle),NULL);
  g_signal_connect ((gpointer) proposed_action_list1,"toggled",G_CALLBACK(on_proposed_action_list_toggle),NULL);
  g_signal_connect ((gpointer) action_list1,"toggled",G_CALLBACK(on_action_list_toggle),NULL);
  g_signal_connect ((gpointer) hide_all,"activate",G_CALLBACK(on_hide_all_clicked),NULL);
  g_signal_connect ((gpointer) show_all,"activate",G_CALLBACK(on_show_all_clicked),NULL);
  g_signal_connect (G_OBJECT(mainWindow),"unmap-event",G_CALLBACK(on_hide_clicked),NULL);
    
  
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, menubar2, "menubar2");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, nuovo1, "nuovo1");
  GLADE_HOOKUP_OBJECT (mainWindow, apri1, "apri1");
  GLADE_HOOKUP_OBJECT (mainWindow, salva1, "salva1");
  GLADE_HOOKUP_OBJECT (mainWindow, salva_come1, "salva_come1");
  GLADE_HOOKUP_OBJECT (mainWindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainWindow, esci1, "esci1");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem6_menu, "menuitem6_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, crisp_data_list1, "crisp_data_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, fuzzy_data_list1, "fuzzy_data_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, weight_want_list1, "weight_want_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, command_list1, "command_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, predicate_list1, "predicate_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, proposed_action_list1, "proposed_action_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, action_list1, "action_list1");
  GLADE_HOOKUP_OBJECT (mainWindow, hide_all, "hide_all");
  GLADE_HOOKUP_OBJECT (mainWindow, show_all, "show_all");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, about1, "about1");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, title, "title");
  GLADE_HOOKUP_OBJECT (mainWindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (mainWindow, fuzzyassoc, "fuzzyassoc");
  GLADE_HOOKUP_OBJECT (mainWindow, fuzzyshapes, "fuzzyshapes");
  GLADE_HOOKUP_OBJECT (mainWindow, defuzzyassoc, "defuzzyassoc");
  GLADE_HOOKUP_OBJECT (mainWindow, defuzzyshapes, "defuzzyshapes");
  GLADE_HOOKUP_OBJECT (mainWindow, behaviors, "behaviors");
  GLADE_HOOKUP_OBJECT (mainWindow, cando, "cando");
  GLADE_HOOKUP_OBJECT (mainWindow, want, "want");
  GLADE_HOOKUP_OBJECT (mainWindow, pries, "pries");
  GLADE_HOOKUP_OBJECT (mainWindow, actionpries, "actionpries");
  GLADE_HOOKUP_OBJECT (mainWindow, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (mainWindow, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (mainWindow, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (mainWindow, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (mainWindow, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (mainWindow, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (mainWindow, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (mainWindow, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (mainWindow, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (mainWindow, browse1, "browse1");
  GLADE_HOOKUP_OBJECT (mainWindow, browse2, "browse2");
  GLADE_HOOKUP_OBJECT (mainWindow, browse3, "browse3");
  GLADE_HOOKUP_OBJECT (mainWindow, browse4, "browse4");
  GLADE_HOOKUP_OBJECT (mainWindow, browse5, "browse5");
  GLADE_HOOKUP_OBJECT (mainWindow, browse6, "browse6");
  GLADE_HOOKUP_OBJECT (mainWindow, browse7, "browse7");
  GLADE_HOOKUP_OBJECT (mainWindow, browse8, "browse8");
  GLADE_HOOKUP_OBJECT (mainWindow, browse9, "browse9");
  GLADE_HOOKUP_OBJECT (mainWindow, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, addCrisp, "addCrisp");
  GLADE_HOOKUP_OBJECT (mainWindow, createBrian, "createBrian");
  GLADE_HOOKUP_OBJECT (mainWindow, runBrian, "runBrian");
  GLADE_HOOKUP_OBJECT (mainWindow, resetBrian, "resetBrian");
  GLADE_HOOKUP_OBJECT (mainWindow, statusbar1, "statusbar1");
    
  gtk_window_add_accel_group (GTK_WINDOW (mainWindow), accel_group);
   
  return mainWindow;
}
