/* Auto-generated by genmsg_cpp for file /home/marcello/robotower/Echoes/msg/Towers.msg */
#ifndef ECHOES_MESSAGE_TOWERS_H
#define ECHOES_MESSAGE_TOWERS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Echoes
{
template <class ContainerAllocator>
struct Towers_ {
  typedef Towers_<ContainerAllocator> Type;

  Towers_()
  : isTowerDestroyed(0)
  , destroyedFactories(0)
  {
  }

  Towers_(const ContainerAllocator& _alloc)
  : isTowerDestroyed(0)
  , destroyedFactories(0)
  {
  }

  typedef int8_t _isTowerDestroyed_type;
  int8_t isTowerDestroyed;

  typedef int8_t _destroyedFactories_type;
  int8_t destroyedFactories;


private:
  static const char* __s_getDataType_() { return "Echoes/Towers"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "320b7d3f9b63efbcdce4894d7f51a261"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 isTowerDestroyed\n\
int8 destroyedFactories\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, isTowerDestroyed);
    ros::serialization::serialize(stream, destroyedFactories);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, isTowerDestroyed);
    ros::serialization::deserialize(stream, destroyedFactories);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(isTowerDestroyed);
    size += ros::serialization::serializationLength(destroyedFactories);
    return size;
  }

  typedef boost::shared_ptr< ::Echoes::Towers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Echoes::Towers_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Towers
typedef  ::Echoes::Towers_<std::allocator<void> > Towers;

typedef boost::shared_ptr< ::Echoes::Towers> TowersPtr;
typedef boost::shared_ptr< ::Echoes::Towers const> TowersConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Echoes::Towers_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Echoes::Towers_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Echoes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Echoes::Towers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Echoes::Towers_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Echoes::Towers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "320b7d3f9b63efbcdce4894d7f51a261";
  }

  static const char* value(const  ::Echoes::Towers_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x320b7d3f9b63efbcULL;
  static const uint64_t static_value2 = 0xdce4894d7f51a261ULL;
};

template<class ContainerAllocator>
struct DataType< ::Echoes::Towers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Echoes/Towers";
  }

  static const char* value(const  ::Echoes::Towers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Echoes::Towers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 isTowerDestroyed\n\
int8 destroyedFactories\n\
\n\
";
  }

  static const char* value(const  ::Echoes::Towers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Echoes::Towers_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Echoes::Towers_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.isTowerDestroyed);
    stream.next(m.destroyedFactories);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Towers_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Echoes::Towers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Echoes::Towers_<ContainerAllocator> & v) 
  {
    s << indent << "isTowerDestroyed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.isTowerDestroyed);
    s << indent << "destroyedFactories: ";
    Printer<int8_t>::stream(s, indent + "  ", v.destroyedFactories);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ECHOES_MESSAGE_TOWERS_H

